### ISSUE TITLE
Drive (Sheets) - Background flips to white

### ISSUE THREAD

**Issue by birsch** [liorgrossman/darkness#107]
See below - loads nicely with a dark background, but 1sec in, and some JS event paints it white again

![image](https://user-images.githubusercontent.com/375099/49825868-230c6b80-fd8e-11e8-8573-1dd669e0c17e.png)

**Comment by theme1256** [comment]
This is performing as intended.  
I did it like that on pupose, so that it would be possible to perform color-work in a document.  
If you've tried the dark theme for MS Office it does the exact same thing.  
The reason for the shift is that the page hasn't finished loading and therefore hasn't injected and applied all the CSS.
