### ISSUE TITLE
Issue with gulp 3.9.1

### ISSUE THREAD

**Issue by a19i23** [liorgrossman/darkness#111]
I get a vulnerability because of some of the packages. Please help. I tried updating to gulp 4.0 but that caused problems. New npm user so not sure how to fix this. Thankyou for any help.
![image](https://user-images.githubusercontent.com/6509090/50028213-c2567c00-ffa3-11e8-85bc-8faf0145c600.png)

![image](https://user-images.githubusercontent.com/6509090/50028343-3d1f9700-ffa4-11e8-8f94-31b22f4f0b75.png)

![image](https://user-images.githubusercontent.com/6509090/50028378-62140a00-ffa4-11e8-9fba-c410e9d861fe.png)

I've tried to run `npm install --save-dev gulp@4.0.0` and it install but then I run `npm install` and darkness breaks by showing this 
![screen shot 2018-12-14 at 1 31 56 pm](https://user-images.githubusercontent.com/6509090/50028501-b6b78500-ffa4-11e8-8331-3fdf938f6735.png)

**Comment by a19i23** [comment]
Oh!... well from the console outputs I get it looks like it's minimatch. I can't say for sure as I'm a total newbie when it comes to npm and this kind of stuff. I was hoping that you could decipher the problem from these outputs. 

I'm actually just running on  macOS. The terminal I use is called iTerm. I like it because you can totally customize it and I use something called oh-my-zsh which also allows for customization.

**Comment by liorgrossman** [comment]
iTerms look really cool, will give it a shot.
According to this issue https://github.com/gulpjs/gulp/issues/1571 - the DoS warning are shown since gulp depends on an old version of graceful-fs (gulp depends on graceful-fs depends on minimatch), and it's nothing to worry about since this code is used only in development.
That would be a concern if you'd use the same library in a production webserver, which could possibly make it vulnerable to DoS attacks. However, this code is not used in a webserver, nor it is used in production. It only runs on your local machine without handling any outside HTTP requests.
Since we can safely ignore this warning, I'm closing this issue.

**Comment by a19i23** [comment]
Ahh I see. That makes sense. I appreciate the work you put into helping me
understand this. Cheers
