### ISSUE TITLE
Google Drive share dialog

### ISSUE THREAD

**Issue by qtest84** [liorgrossman/darkness#116]
**Is your feature request related to a problem you've encountered? Please describe.**
When I use google drive share dialog, the CSS style seems not to apply to the permission control dialog,
please kindly help to check, thank you.

**Describe the solution you'd like to see**
Just fix it during open the permission dialog.

**Comment by theme1256** [comment]
This one is a difficult one.  
The problem is that the CSS isn't applied to `<iframe>`.

@liorgrossman any news on how to get this working? I know that I've brought it up before :)

**Comment by liorgrossman** [comment]
@theme1256 that's right.
Us use executeScript to inject our scripts. We set the allFrames parameter to false to avoid executing in iFrames:
`chrome.tabs.executeScript(tab.id, {
				code: code,
				runAt: 'document_start',
				allFrames: false // not in iframes
			});`
If I recall correctly, the main reason is that we don't want to run the entire Darkness logic (including showing the icon and menus) for all iframes.
Theoretically, the solution would be to detect if we're inside an iframe, and conditionally load only part of the logic (the part that darkens the page) and not other parts of the logic (icon and menus).
That is quite a major change which could introduce other bugs.
@theme1256 - do you remember where else did we encounter unskinned parts of the screen due to this iframe limitation? Is it common?

**Comment by theme1256** [comment]
@liorgrossman   
As far as I remember, it's only on google sites.  
Most of google's popups are inside iframe, but only sometimes, it depends on what features are available in the browser and if it managed to load some of the JS-scripts, I think.

**Comment by liorgrossman** [comment]
Solving this requires significant logic changes on how Darkness operates on iframes, which runs the risk of introducing additional websites.
While this is definitely an annoyance, I believe people don't stare at the share dialog for long periods of time.
Therefore, I think we will not be able to fix this bug at the moment, sorry @qtest84.
