### ISSUE TITLE
Google Photos Backspace Dysfunctional

### ISSUE THREAD

**Issue by tokyojerry** [liorgrossman/darkness#118]
When using the darkness extension in Google Photos, and attempting to return to the previous screen (i.e. left arrow to go from album details to album / photos display) the left button no longer works when darness is  enabled.  If darness disable, the back space key works just fine.

**Comment by theme1256** [comment]
Just had a look at this.  
It seems that this is only a problem when the theme is activated before an image has been opened.  
If the theme is toggled or enabled while an image is open, the button works.  
@liorgrossman Any idea?

**Comment by liorgrossman** [comment]
I tried looking at the DOM elements for the toolbar, and they look 100% the same on 2 different tabs, one with Darkness enabled and one with Darkness disabled.
So I figured this must be some CSS we apply causing this.
Since I had no idea where to start, I basically started stripping down all CSS from googlephotos.scss and all-websites.scss gradually, and see if that solves the problem.
Eventually, I found the curlpit in all-websites.scss:
```
// Un-invert images and video
img,
iframe,
video,
embed:not([type$="pdf"]),
object,
svg,
canvas,
[background*="http"] {
	@include invert-back()
}
```
This code inverts all the SVG icons in the toolbar.
From some reason, still not sure why, the back button doesn't respond when it has a CSS invert filter applied. I noticed it doesn't even work when the button has opacity, weird.

The solution (workaround?) is to disable the filter for that specific button, then fix its style.

Committed a fix and will deploy shortly
https://github.com/liorgrossman/darkness/commit/8bd221422fbfe7dd537d515c129689fddbe2a738
