### ISSUE TITLE
Darkness Pro is bugged and can't use

### ISSUE THREAD

**Issue by lespaul678** [liorgrossman/darkness#119]
* Site: twitter
* Theme: base16tomorrow
* URL: https://twitter.com/WOWCare
* Darkness Version: 2.0.5 Pro
* Browser: Chrome 71.0.3578.98
* Operating System: Windows 10
* Resolution: 2048x1152
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Every site I use this extension on doesn't work very well.  It ends up looking like the "negative" of a photograph and makes most things very difficult and "weird" to read.  Also most of the time makes text even more difficult to read.

edit ** on this website it looks incredible.  I can't get results like this on any other website, but on this page, it looks awesome.

**Comment by liorgrossman** [comment]
Hi @lespaul678
I'm not sure we can help much without concrete examples.
Looking at the URL you attached, it looks perfectly inverted (no negative photographs, etc.)
If you encounter specific problems with inverted images or text on other websites, please open a separate issue, and attach a screenshot to demonstrate where the problem is.
Many thanks.
