### ISSUE TITLE
Ms

### ISSUE THREAD

**Issue by hollyjorose** [liorgrossman/darkness#250]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: 
* Theme: 
* URL: 
* Darkness Version: 
* Browser: 
* Operating System: I can't shut Darkness off so that I can print a page with a light background instead of the dark background
* 

**Bug Description**
Please provide a clear description of what the bug or issue is.

**Screenshots**
If necessary, add screenshots to help explain your problem.

**Comment by liorgrossman** [comment]
Hi Holly.

In order to disable Darkness for a specified site, you need to:

1. Click the moon icon in the top-right corner of the website
![image](https://user-images.githubusercontent.com/987284/147892179-afa96f82-9355-44c3-8651-33a87279f22b.png)

2. In the Darkness dialog, click "No Theme":
![image](https://user-images.githubusercontent.com/987284/147892196-feb508c9-985e-4496-99bc-0c26916d3f74.png)

This should allow you to print the page as-is without the dark theme.

Alternatively, you can open an Incognito window: https://support.google.com/chrome/answer/95464?hl=en&co=GENIE.Platform%3DDesktop

Darkness isn't active in Incognito windows, so you should be able to print the page as-is from there.
