### ISSUE TITLE
Amazon - Dropdown Menu not visible

### ISSUE THREAD

**Issue by Seriell** [liorgrossman/darkness#50]
![image](https://i.fl0.co/6b4a71.gif)

**Comment by theme1256** [comment]
The theme is in development, so I understand why it is not working, it is clearly not finished.

If you check the commit history there hasn't been a commit with changes to that theme since it was started.

**Comment by liorgrossman** [comment]
Yep, we mark those themes as "in-development", since they are not ready for usage yet, but it's still and opportunity to collaborate on creating those skins.
You can see it in:
https://github.com/liorgrossman/darkness/blob/master/chrome-extension/js/background/config.js
The Wikipedia, Google Drive and Twitch skins are also "in-development" stage, since they still require some work until they're ready for prime time.

I'm closing this ticket for now, since there are probably a dozen thing that still need to be fixes in the Amazon skin, by definition.
