### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by bitboxer** [liorgrossman/darkness#71]
Have you thought of also packaging this for firefox? Firefox also uses WebExtensions and there are only minor differences in both. Mostly in the manifest file.

**Comment by liorgrossman** [comment]
Hey Bodo.

Porting Darkness for Firefox might not be very difficult, since it supports WebExtensions.

However, we haven't seen a lot of demand for it (very few people asked for Firefox support over the course of 1.5 years).

Since websites' CSS change frequently, Darkness requires frequent updates to the various skins (15+ websites).
I think having every commit in the project tested and verified to work with both Firefox and Chrome would make things harder. @theme1256 - what do you think?

**Comment by bitboxer** [comment]
Maybe separating the css files from the releases might help with this?

**Comment by theme1256** [comment]
Usually, websites use the same frontend and then it doesn't matter what browser it is, but som of the sites we skin, I'm not sure about.

I might be more work for some of the skins and we might have the go through and find all the `-webkit` code, because, as far as I remember, Mozilla created their own CSS system called `moz`, but they might support webkit.

It's a good idea since a lot of devs is moving back to FireFox, now that it has gotten a lot better and Chrome is ups and downs.

**Comment by bitboxer** [comment]
I just scrolled through the hits when searching for "-webkit" here and I think it should work. You are using "-webkit-filter" a lot with the inverse filter. According to the mozilla documentation this is supported with the "-webkit"  namespace. See [here](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) for details.

**Comment by liorgrossman** [comment]
Yes, Firefox Quantum is pretty damn good, and I saw many people giving Firefox a try lately.
In any case, we use SCSS (and not pure CSS), so we can use mixins to add browser vendor prefix, or even use something like this: https://github.com/postcss/autoprefixer
I'm still not sure it will work out of the box, since FIrefox and Chrome handle CSS rules differently and aren't 100% compatible.

Might be worth a try and just seeing just how many errors/problems occur. It might prove to be harder or easier than expected. Unfortunately, I'm over-capacity at the moment to do this port at the moment, but I'll support this kind of port if you wish to pursue it, and help with any questions you may have.

**Comment by liorgrossman** [comment]
A good first step might be just trying to load the "chrome-extension" directory it into Firefox and see if it works, possibly creating a copy of the existing manifest file.

**Comment by raywhui** [comment]
Hi! This is my first time contributing to an open source project, so I may not know all the rules to helping out. 

So I did manage to get the Darkness Developer Edition to run on Mozilla (v 58.0.2 as of writing this). The process was very straight forward and didn't require a lot of changes to the code to get it to work. The only significant changes that were made was changing any instance of `chrome.storage.sync` to `chrome.storage.local` in `js/user-settings.js` and `js/user-stats.js`. There apparently is a way to get `chrome.storage.sync` to work, but requires a GUID provided by Mozilla that is blocklisted for some reason.

**Comment by liorgrossman** [comment]
Thanks for investigating this @raywhui!
Great to see Darkness working inside Firefox Quantum.
Seems like most of the changes are relatively minor.
I just saw your pull request, will reply there shortly:
https://github.com/liorgrossman/darkness/pull/72

**Comment by liorgrossman** [comment]
Hey guys, thanks again for your help.
I just added Firefox support to Darkness. It might not be perfect, but it's a start.
Running `gulp ff` will copy and transform the chrome-extension directory to firefox-extension, which you could load from Firefox.
I have added instructions in the README and CONTRIBUTING docs.

**Comment by heatr216** [comment]
Not sure it matters but I would absolutely love a Firefox version in the Extensions "store" like Chrome has. I have to use Firefox at work to avoid having my Google account managed by my organization. Therefore, I lose out on Darkness in Chrome for my own gmail/facebook. Using FF Quantum, I miss the extension. Just my two-cents. LOVE the Chrome version. Thank you.
