### ISSUE TITLE
Inverted gifs on twitter

### ISSUE THREAD

**Issue by yuletide** [liorgrossman/darkness#82]
Will look into it now and see if I can figure out how to whitelist elements or images!
Here's an example: ![img](https://cl.ly/1j0r0J3t002U/Image%202018-08-01%20at%201.03.46%20PM.png)

**Comment by liorgrossman** [comment]
Thanks Alex.
I'd start by inspecting the "affected" element with Chrome Developer Tools.

Darkness works by inverting the entire page <HTML> with filter:invert(1), then inverting back all elements which need to retain their original colors (e.g. imgs, videos, etc.)

Therefore, such a problem could be either:
1. **invert-back is necessary and missing**: the element needs to be inverted back, but isn't. Inverting back is done by creating a selector in twitter.scss, e.g.
```
.twitterGifSelector { 
  @include invert-back();
}
```
2. **invert-back is unnecessarily used**: it could be that we invert-back() this element although it doesn't need to be inverted back.
This happens when a selector is too wide, for example: img { @include invert-back() }
In such case, you could exclude this specific element from being inverted back:
```
img { 
  @include invert-back();
  .twitterGifSelector {
    filter: none !important;
  }
}
```

**Comment by sheldonhull** [comment]
@liorgrossman  is the proper approach to do the statement above or to use something like 

```css
img:not(.twitterGifSelector)
```
Trying to learn how to edit properly and wanting to make sure that what you said above minimizes the flipping back and forth less than the other `not` syntax.  Been editing a few new themes to push soon and realized a few things like this are confusing me.

**Comment by liorgrossman** [comment]
Both are valid options and both will work :)
Not sure which one will provide better performance, frankly.
Your syntax will produce a small CSS, that's for sure, so feel free to use it.
